name: Develop CI

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - 'demo/**'

jobs:
  develop-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Website
        run: yarn build

      - name: Build Website
        run: yarn build
