name: Feat CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'demo/**'

jobs:
  feat-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3

      - name: Step Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run bootstrap

      - name: Build Website
        run: pnpm run build
